feat: allow optional response status code validation
fastify/fastify-response-validation pull request #98
Opened 2023-07-26 12:11 UTC by sceccotti89

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-07-28 09:11 UTC, mcollina commented
Can you please fix the linting?

2023-07-28 09:17 UTC, sceccotti89 commented
@mcollina Fixed.

2023-07-28 09:26 UTC, mcollina commented
Can you please add a test for the type https://github.com/fastify/fastify-response-validation/blob/master/types/index.test-d.ts?

2023-07-28 09:32 UTC, sceccotti89 commented
@mcollina Thanks for the feedback. Test added.

2023-07-28 09:46 UTC, mcollina approved these changes
lgtm

2023-07-31 09:29 UTC, sceccotti89 commented
My last forced push commit was to solve the linting issue. It should all be fine now.

2023-07-31 09:42 UTC, Uzlopak commented on index.js
> +      const responseStatusCodeValidation = routeOpts.responseStatusCodeValidation || opts.responseStatusCodeValidation
```suggestion
      const responseStatusCodeValidation = routeOpts.responseStatusCodeValidation || opts.responseStatusCodeValidation || false
```

2023-07-31 09:42 UTC, Uzlopak commented on index.js
> +      if (validate === undefined && responseStatusCodeValidation) {
```suggestion
      if (responseStatusCodeValidation && validate === undefined) {
```

2023-07-31 09:44 UTC, Uzlopak requested changes
I personally would have created another preSerialization Hook Handler for the case of responseStatusCodeValidation was true. But I would say, that by setting the responseStatusCodeValidation fallback to false it v8 optimizer has a chance to optimize it.

2023-07-31 09:56 UTC, sceccotti89 commented
@Uzlopak PR updated.

2023-07-31 10:01 UTC, Uzlopak approved these changes
LGTM

2023-08-07 08:01 UTC, sceccotti89 commented
Hi guys. Any chance this can get merged soon?

2023-08-07 17:05 UTC, merged